# Generated by Django 4.1.3 on 2022-11-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-01-01'),
            preserve_default=False,
        ),
    ]
