# Generated by Django 4.1.3 on 2022-11-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_remove_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=5464),
            preserve_default=False,
        ),
    ]
